### ISSUE TITLE
News Ticker data

### ISSUE THREAD

**Issue by makeworld-the-better-one** [robbiebyrd/rt911#26]
Where is the data from the News Ticker? It'd be nice to have that available to read through separately. Thanks! Amazing project.

**Comment by robbiebyrd** [comment]
It comes from historycommons.org. It has been scraped and sanitized, and most items that were not given a hard time stamp were eliminated. Later this evening I will upload my scraping utilities and come back here with a better explanation of where I got that data.

**Comment by makeworld-the-better-one** [comment]
Sounds good, thanks!
